package main

import "github.com/gotranspile/cxgo/runtime/libc"

var pk_allowed int = NO
var pt_allowed int = NO
var level_can_shout int = 1
var holler_move_cost int = 20
var CURRENT_ERA int = 8
var mob_specials_used int = 0
var number_of_assassins int = 0
var last_user_freed [2048]byte
var TOPLOADED int = FALSE
var topname [25]*byte
var toppoint [25]int64 = [25]int64{}
var ERAPLAYERS int = 0
var TOPCOUNTDOWN int = 60
var HEDITS int = FALSE
var WISHTIME int = 0
var TOP_OF_NEWS int = 0
var NEWS_TITLE *byte
var BOARDNEWMORT libc.Time = 0
var BOARDNEWIMM libc.Time = 0
var BOARDNEWCOD libc.Time = 0
var BOARDNEWDUO libc.Time = 0
var BOARDNEWBUI libc.Time = 0
var NEWSUPDATE libc.Time = 0
var INTERESTTIME libc.Time = 0
var LASTINTEREST libc.Time = 0
var LASTPAYOUT libc.Time = 0
var LASTNEWS int = 0
var LASTPAYTYPE int = 0
var SAIYAN_ALLOWED int = FALSE
var MAJIN_ALLOWED int = FALSE
var MOON_UP int = FALSE
var DEATHPHASE int = FALSE
var PCOUNT int = 0
var HIGHPCOUNT int = 0
var PCOUNTDATE libc.Time = 0
var PCOUNTDAY libc.Time = 0
var SELFISHMETER int = 0
var SHADOW_DRAGON1 int = -1
var SHADOW_DRAGON2 int = -1
var SHADOW_DRAGON3 int = -1
var SHADOW_DRAGON4 int = -1
var SHADOW_DRAGON5 int = -1
var SHADOW_DRAGON6 int = -1
var SHADOW_DRAGON7 int = -1
var DBALL_HUNTER1 int = -1
var DBALL_HUNTER2 int = -1
var DBALL_HUNTER3 int = -1
var DBALL_HUNTER4 int = -1
var DBALL_HUNTER1_VNUM int = 88
var DBALL_HUNTER2_VNUM int = 89
var DBALL_HUNTER3_VNUM int = 0
var DBALL_HUNTER4_VNUM int = 0
var tunnel_size int = 2
var max_exp_gain int = 1000000
var max_exp_loss int = 250000
var max_npc_corpse_time int = 5
var max_pc_corpse_time int = 10
var idle_void int = 8
var idle_rent_time int = 48
var idle_max_level int = ADMLVL_IMMORT
var dts_are_dumps int = YES
var pulse_violence int = 5
var pulse_zone int = 10
var pulse_mobile int = 10
var pulse_autosave int = 60
var pulse_idlepwd int = 15
var pulse_sanity int = 30
var pulse_usage int = 5
var pulse_timesave int = 30
var pulse_current int = 10
var load_into_inventory int = NO
var OK *byte = libc.CString("Okay.\r\n")
var NOPERSON *byte = libc.CString("No-one by that name here.\r\n")
var NOEFFECT *byte = libc.CString("Nothing seems to happen.\r\n")
var track_through_doors int = YES
var level_cap int = 101
var show_obj_stacking int = YES
var show_mob_stacking int = YES
var mob_fighting int = NO
var imc_is_enabled int = NO
var free_rent int = YES
var max_obj_save int = 30
var min_rent_cost int = 100
var auto_save int = YES
var autosave_time int = 1
var crash_file_timeout int = 10
var rent_file_timeout int = 30
var auto_pwipe int = YES
var pclean_criteria [7]pclean_criteria_data = [7]pclean_criteria_data{{}, {Level: 1, Days: 30}, {Level: 4, Days: 90}, {Level: 10, Days: 180}, {Level: 50, Days: 360}, {Level: 100, Days: 360}, {Level: -1, Days: 0}}
var selfdelete_fastwipe int = YES
var death_start_room room_vnum = 6000
var mortal_start_room room_vnum = 2
var immort_start_room room_vnum = 2
var frozen_start_room room_vnum = 2
var donation_room_1 room_vnum = 3063
var donation_room_2 room_vnum = room_vnum(-1)
var donation_room_3 room_vnum = room_vnum(-1)
var bitwarning int = FALSE
var bitsavetodisk int = TRUE
var DFLT_PORT uint16 = 5001
var DFLT_IP *byte = nil
var DFLT_DIR *byte = libc.CString("lib")
var LOGNAME *byte = nil
var max_playing int = 300
var max_filesize int = 50000
var max_bad_pws int = 3
var siteok_everyone int = TRUE
var nameserver_is_slow int = NO
var ANSIQUESTION *byte = libc.CString("Do you support the ANSI color standard (Yn)? ")
var auto_save_olc int = 1
var use_new_socials int = 1
var MENU *byte = libc.CString("\r\n@GWelcome to @YCircleMUD!@n\r\n@B0@W) @CExit from @YCircleMUD.@n\r\n@B1@W) @CEnter the game.@n\r\n@B2@W) @CEnter description.@n\r\n@B3@W) @CGame Info (Please Read)@n\r\n@B4@W) @CChange password.@n\r\n@B5@W) @CDelete this character.@n\r\n\r\n   @WMake your choice: @n")
var WELC_MESSG *byte = libc.CString("\r\nWelcome to the land of CircleMUD!  May your visit here be... Interesting.\r\n\r\n")
var START_MESSG *byte = libc.CString("Welcome.  This is your new CircleMUD character!  You can now earn gold,\r\ngain experience, find weapons and equipment, and much more -- while\r\nmeeting people from around the world!\r\n")
var use_autowiz int = YES
var min_wizlist_lev int = ADMLVL_GOD
var portal_object obj_vnum = 2
var initial_points int = 20
var disp_closed_doors int = YES
var reroll_status int = NO
var allow_multiclass int = NO
var allow_prestige int = NO
var auto_level int = YES
var enable_compression int = YES
var enable_languages int = YES
var all_items_unique int = YES
var exp_multiplier float32 = 1.0
var method int = 0
