package main

import (
	"github.com/gotranspile/cxgo/runtime/libc"
	"unsafe"
)

const _CIRCLEMUD = 0x30100
const USE_AUTOEQ = 1
const CWG_VERSION = "CWG Rasputin - 3.5.31"
const DBAT_VERSION = "DBAT - version 2.4"
const SG_MIN = 2
const SONG_SAFETY = 1
const SONG_SHIELDING = 2
const SONG_SHADOW_STITCH = 3
const SONG_TELEPORT_EARTH = 4
const SONG_TELEPORT_KONACK = 5
const SONG_TELEPORT_ARLIA = 6
const SONG_TELEPORT_NAMEK = 7
const SONG_TELEPORT_VEGETA = 8
const SONG_TELEPORT_FRIGID = 9
const SONG_TELEPORT_AETHER = 10
const SONG_TELEPORT_KANASSA = 11
const PREFERENCE_THROWING = 1
const PREFERENCE_H2H = 2
const PREFERENCE_KI = 3
const PREFERENCE_WEAPON = 4
const RCP_TOMATO = 0x433C
const RCP_POTATO = 0x433D
const RCP_ONION = 0x433F
const RCP_CUCUMBER = 0x4341
const RCP_CHILIPEPPER = 0x4343
const RCP_FOUSTAFI = 0x4345
const RCP_CARROT = 0x4347
const RCP_GREENBEAN = 0x4349
const RCP_NORMAL_MEAT = 1612
const RCP_GOOD_MEAT = 6500
const RCP_BLACKBASS = 1000
const RCP_SILVERTROUT = 1001
const RCP_STRIPEDBASS = 1002
const RCP_BLUECATFISH = 1003
const RCP_FLOUNDER = 1004
const RCP_SILVEREEL = 1005
const RCP_COBIA = 1006
const RCP_TAMBOR = 1007
const RCP_NARRI = 1008
const RCP_VALBISH = 1009
const RCP_GUSBLAT = 1010
const RCP_REPEEIL = 1011
const RCP_GRAVELREBOI = 1012
const RCP_VOOSPIKE = 1013
const RCP_SHADOWFISH = 1014
const RCP_SHADEEEL = 1015
const RCP_BROWNMUSH = 1608
const RCP_GARLIC = 1131
const RCP_RICE = 1590
const RCP_FLOUR = 1591
const RCP_LETTUCE = 0x434B
const RCP_APPLEPLUM = 8001
const RCP_FROZENBERRY = 4901
const RCP_CARAMBOLA = 3416
const RECIPE_TOMATO_SOUP = 1
const RECIPE_POTATO_SOUP = 2
const RECIPE_VEGETABLE_SOUP = 3
const RECIPE_MEAT_STEW = 4
const RECIPE_STEAK = 5
const RECIPE_ROAST = 6
const RECIPE_CHILI_SOUP = 7
const RECIPE_GRILLED_NORMFISH = 8
const RECIPE_GRILLED_GOODFISH = 9
const RECIPE_GRILLED_GREATFISH = 10
const RECIPE_GRILLED_BESTFISH = 11
const RECIPE_COOKED_RICE = 12
const RECIPE_SUSHI = 13
const RECIPE_BREAD = 14
const RECIPE_SALAD = 15
const RECIPE_APPLEPLUM = 16
const RECIPE_FBERRY_MUFFIN = 17
const RECIPE_CARAMBOLA_BREAD = 18
const MEAL_START = 1220
const MEAL_TOMATO_SOUP = 1220
const MEAL_STEAK = 1221
const MEAL_POTATO_SOUP = 1222
const MEAL_VEGETABLE_SOUP = 1223
const MEAL_MEAT_STEW = 1224
const MEAL_ROAST = 1225
const MEAL_CHILI_SOUP = 1226
const MEAL_NORM_FISH = 1227
const MEAL_GOOD_FISH = 1228
const MEAL_GREAT_FISH = 1229
const MEAL_BEST_FISH = 1230
const MEAL_COOKED_RICE = 1231
const MEAL_SUSHI = 1232
const MEAL_BREAD = 1233
const MEAL_SALAD = 1234
const MEAL_APPLEPLUM = 1235
const MEAL_FBERRY_MUFFIN = 1236
const MEAL_CARAMBOLA_BREAD = 1237
const MEAL_LAST = 1234
const FISH_NOFISH = 0
const FISH_BITE = 1
const FISH_HOOKED = 2
const FISH_REELING = 3
const SHADOW_DRAGON1_VNUM = 81
const SHADOW_DRAGON2_VNUM = 82
const SHADOW_DRAGON3_VNUM = 83
const SHADOW_DRAGON4_VNUM = 84
const SHADOW_DRAGON5_VNUM = 85
const SHADOW_DRAGON6_VNUM = 86
const SHADOW_DRAGON7_VNUM = 87
const NORTH = 0
const EAST = 1
const SOUTH = 2
const WEST = 3
const UP = 4
const DOWN = 5
const NORTHWEST = 6
const NORTHEAST = 7
const SOUTHEAST = 8
const SOUTHWEST = 9
const INDIR = 10
const OUTDIR = 11
const ROOM_DARK = 0
const ROOM_DEATH = 1
const ROOM_NOMOB = 2
const ROOM_INDOORS = 3
const ROOM_PEACEFUL = 4
const ROOM_SOUNDPROOF = 5
const ROOM_NOTRACK = 6
const ROOM_NOINSTANT = 7
const ROOM_TUNNEL = 8
const ROOM_PRIVATE = 9
const ROOM_GODROOM = 10
const ROOM_HOUSE = 11
const ROOM_HOUSE_CRASH = 12
const ROOM_ATRIUM = 13
const ROOM_OLC = 14
const ROOM_BFS_MARK = 15
const ROOM_VEHICLE = 16
const ROOM_UNDERGROUND = 17
const ROOM_CURRENT = 18
const ROOM_TIMED_DT = 19
const ROOM_EARTH = 20
const ROOM_VEGETA = 21
const ROOM_FRIGID = 22
const ROOM_KONACK = 23
const ROOM_NAMEK = 24
const ROOM_NEO = 25
const ROOM_AL = 26
const ROOM_SPACE = 27
const ROOM_HELL = 28
const ROOM_REGEN = 29
const ROOM_RHELL = 30
const ROOM_GRAVITYX10 = 31
const ROOM_AETHER = 32
const ROOM_HBTC = 33
const ROOM_PAST = 34
const ROOM_CBANK = 35
const ROOM_SHIP = 36
const ROOM_YARDRAT = 37
const ROOM_KANASSA = 38
const ROOM_ARLIA = 39
const ROOM_AURA = 40
const ROOM_EORBIT = 41
const ROOM_FORBIT = 42
const ROOM_KORBIT = 43
const ROOM_NORBIT = 44
const ROOM_VORBIT = 45
const ROOM_AORBIT = 46
const ROOM_YORBIT = 47
const ROOM_KANORB = 48
const ROOM_ARLORB = 49
const ROOM_NEBULA = 50
const ROOM_ASTERO = 51
const ROOM_WORMHO = 52
const ROOM_STATION = 53
const ROOM_STAR = 54
const ROOM_CERRIA = 55
const ROOM_CORBIT = 56
const ROOM_BEDROOM = 57
const ROOM_WORKOUT = 58
const ROOM_GARDEN1 = 59
const ROOM_GARDEN2 = 60
const ROOM_FERTILE1 = 61
const ROOM_FERTILE2 = 62
const ROOM_FISHING = 63
const ROOM_FISHFRESH = 64
const ROOM_CANREMODEL = 65
const NUM_ROOM_FLAGS = 66
const ZONE_CLOSED = 0
const ZONE_NOIMMORT = 1
const ZONE_QUEST = 2
const ZONE_DBALLS = 3
const ZONE_SPARE2 = 4
const ZONE_SPARE3 = 5
const ZONE_SPARE4 = 6
const ZONE_SPARE5 = 7
const ZONE_SPARE6 = 8
const ZONE_SPARE7 = 9
const ZONE_SPARE8 = 10
const ZONE_SPARE9 = 11
const ZONE_SPARE10 = 12
const ZONE_SPARE11 = 13
const ZONE_SPARE12 = 14
const ZONE_SPARE13 = 15
const ZONE_SPARE14 = 16
const ZONE_SPARE15 = 17
const ZONE_SPARE16 = 18
const ZONE_SPARE17 = 19
const ZONE_SPARE18 = 20
const ZONE_SPARE19 = 21
const ZONE_SPARE20 = 22
const ZONE_SPARE21 = 23
const ZONE_SPARE22 = 24
const ZONE_SPARE23 = 25
const ZONE_SPARE24 = 26
const ZONE_SPARE25 = 27
const ZONE_SPARE26 = 28
const ZONE_SPARE27 = 29
const ZONE_SPARE28 = 30
const ZONE_SPARE29 = 31
const ZONE_SPARE30 = 32
const ZONE_SPARE31 = 33
const ZONE_SPARE32 = 34
const ZONE_SPARE33 = 35
const EX_ISDOOR = 1
const EX_CLOSED = 2
const EX_LOCKED = 4
const EX_PICKPROOF = 8
const EX_SECRET = 16
const NUM_EXIT_FLAGS = 5
const SECT_INSIDE = 0
const SECT_CITY = 1
const SECT_FIELD = 2
const SECT_FOREST = 3
const SECT_HILLS = 4
const SECT_MOUNTAIN = 5
const SECT_WATER_SWIM = 6
const SECT_WATER_NOSWIM = 7
const SECT_FLYING = 8
const SECT_UNDERWATER = 9
const SECT_SHOP = 10
const SECT_IMPORTANT = 11
const SECT_DESERT = 12
const SECT_SPACE = 13
const SECT_LAVA = 14
const NUM_ROOM_SECTORS = 15
const CLASS_UNDEFINED = -1
const CLASS_ROSHI = 0
const CLASS_PICCOLO = 1
const CLASS_KRANE = 2
const CLASS_NAIL = 3
const CLASS_BARDOCK = 4
const CLASS_GINYU = 5
const CLASS_FRIEZA = 6
const CLASS_TAPION = 7
const CLASS_ANDSIX = 8
const CLASS_DABURA = 9
const CLASS_KABITO = 10
const CLASS_JINTO = 11
const CLASS_TSUNA = 12
const CLASS_KURZAK = 13
const CLASS_ASSASSIN = 14
const CLASS_BLACKGUARD = 15
const CLASS_DRAGON_DISCIPLE = 16
const CLASS_DUELIST = 17
const CLASS_DWARVEN_DEFENDER = 18
const CLASS_ELDRITCH_KNIGHT = 19
const CLASS_HIEROPHANT = 20
const CLASS_HORIZON_WALKER = 21
const CLASS_LOREMASTER = 22
const CLASS_MYSTIC_THEURGE = 23
const CLASS_SHADOWDANCER = 24
const CLASS_THAUMATURGIST = 25
const CLASS_NPC_EXPERT = 26
const CLASS_NPC_ADEPT = 27
const CLASS_NPC_COMMONER = 28
const CLASS_NPC_ARISTOCRAT = 29
const CLASS_NPC_WARRIOR = 30
const MAX_SENSEI = 15
const NUM_CLASSES = 31
const NUM_NPC_CLASSES = 4
const NUM_PRESTIGE_CLASSES = 15
const NUM_BASIC_CLASSES = 14
const GAUNTLET_ZONE = 24
const GAUNTLET_START = 2403
const GAUNTLET_END = 2404
const DTYPE_NORMAL = 0
const DTYPE_HEAD = 1
const DTYPE_HALF = 2
const DTYPE_VAPOR = 3
const DTYPE_PULP = 4
const BONUS_THRIFTY = 0
const BONUS_PRODIGY = 1
const BONUS_QUICK_STUDY = 2
const BONUS_DIEHARD = 3
const BONUS_BRAWLER = 4
const BONUS_DESTROYER = 5
const BONUS_HARDWORKER = 6
const BONUS_HEALER = 7
const BONUS_LOYAL = 8
const BONUS_BRAWNY = 9
const BONUS_SCHOLARLY = 10
const BONUS_SAGE = 11
const BONUS_AGILE = 12
const BONUS_QUICK = 13
const BONUS_STURDY = 14
const BONUS_THICKSKIN = 15
const BONUS_RECIPE = 16
const BONUS_FIREPROOF = 17
const BONUS_POWERHIT = 18
const BONUS_HEALTHY = 19
const BONUS_INSOMNIAC = 20
const BONUS_EVASIVE = 21
const BONUS_WALL = 22
const BONUS_ACCURATE = 23
const BONUS_LEECH = 24
const BONUS_GMEMORY = 25
const BONUS_SOFT = 26
const BONUS_LATE = 27
const BONUS_IMPULSE = 28
const BONUS_SICKLY = 29
const BONUS_PUNCHINGBAG = 30
const BONUS_PUSHOVER = 31
const BONUS_POORDEPTH = 32
const BONUS_THINSKIN = 33
const BONUS_FIREPRONE = 34
const BONUS_INTOLERANT = 35
const BONUS_COWARD = 36
const BONUS_ARROGANT = 37
const BONUS_UNFOCUSED = 38
const BONUS_SLACKER = 39
const BONUS_SLOW_LEARNER = 40
const BONUS_MASOCHISTIC = 41
const BONUS_MUTE = 42
const BONUS_WIMP = 43
const BONUS_DULL = 44
const BONUS_FOOLISH = 45
const BONUS_CLUMSY = 46
const BONUS_SLOW = 47
const BONUS_FRAIL = 48
const BONUS_SADISTIC = 49
const BONUS_LONER = 50
const BONUS_BMEMORY = 51
const MAX_BONUSES = 52
const DISTFEA_EYE = 0
const DISTFEA_HAIR = 1
const DISTFEA_SKIN = 2
const DISTFEA_HEIGHT = 3
const DISTFEA_WEIGHT = 4
const AURA_WHITE = 0
const AURA_BLUE = 1
const AURA_RED = 2
const AURA_GREEN = 3
const AURA_PINK = 4
const AURA_PURPLE = 5
const AURA_YELLOW = 6
const AURA_BLACK = 7
const AURA_ORANGE = 8
const EYE_UNDEFINED = -1
const EYE_BLUE = 0
const EYE_BLACK = 1
const EYE_GREEN = 2
const EYE_BROWN = 3
const EYE_RED = 4
const EYE_AQUA = 5
const EYE_PINK = 6
const EYE_PURPLE = 7
const EYE_CRIMSON = 8
const EYE_GOLD = 9
const EYE_AMBER = 10
const EYE_EMERALD = 11
const HAIRL_UNDEFINED = -1
const HAIRL_BALD = 0
const HAIRL_SHORT = 1
const HAIRL_MEDIUM = 2
const HAIRL_LONG = 3
const HAIRL_RLONG = 4
const HAIRC_UNDEFINED = -1
const HAIRC_NONE = 0
const HAIRC_BLACK = 1
const HAIRC_BROWN = 2
const HAIRC_BLONDE = 3
const HAIRC_GREY = 4
const HAIRC_RED = 5
const HAIRC_ORANGE = 6
const HAIRC_GREEN = 7
const HAIRC_BLUE = 8
const HAIRC_PINK = 9
const HAIRC_PURPLE = 10
const HAIRC_SILVER = 11
const HAIRC_CRIMSON = 12
const HAIRC_WHITE = 13
const HAIRS_UNDEFINED = -1
const HAIRS_NONE = 0
const HAIRS_PLAIN = 1
const HAIRS_MOHAWK = 2
const HAIRS_SPIKY = 3
const HAIRS_CURLY = 4
const HAIRS_UNEVEN = 5
const HAIRS_PONYTAIL = 6
const HAIRS_AFRO = 7
const HAIRS_FADE = 8
const HAIRS_CREW = 9
const HAIRS_FEATHERED = 10
const HAIRS_DRED = 11
const SKIN_UNDEFINED = -1
const SKIN_WHITE = 0
const SKIN_BLACK = 1
const SKIN_GREEN = 2
const SKIN_ORANGE = 3
const SKIN_YELLOW = 4
const SKIN_RED = 5
const SKIN_GREY = 6
const SKIN_BLUE = 7
const SKIN_AQUA = 8
const SKIN_PINK = 9
const SKIN_PURPLE = 10
const SKIN_TAN = 11
const PHASE_PURITY = 0
const PHASE_BRAVERY = 1
const PHASE_HATRED = 2
const PHASE_DOMINANCE = 3
const PHASE_GUARDIAN = 4
const PHASE_LOVE = 5
const PHASE_STRENGTH = 6
const RACE_UNDEFINED = -1
const RACE_HUMAN = 0
const RACE_SAIYAN = 1
const RACE_ICER = 2
const RACE_KONATSU = 3
const RACE_NAMEK = 4
const RACE_MUTANT = 5
const RACE_KANASSAN = 6
const RACE_HALFBREED = 7
const RACE_BIO = 8
const RACE_ANDROID = 9
const RACE_DEMON = 10
const RACE_MAJIN = 11
const RACE_KAI = 12
const RACE_TRUFFLE = 13
const RACE_HOSHIJIN = 14
const RACE_ANIMAL = 15
const RACE_ORC = 16
const RACE_SNAKE = 17
const RACE_TROLL = 18
const RACE_MINOTAUR = 19
const RACE_ARLIAN = 20
const RACE_LIZARDFOLK = 21
const RACE_WARHOST = 22
const RACE_FAERIE = 23
const NUM_RACES = 24
const ALIGN_SAINT = 0
const ALIGN_VALIANT = 1
const ALIGN_HERO = 2
const ALIGN_DOGOOD = 3
const ALIGN_NEUTRAL = 4
const ALIGN_CROOK = 5
const ALIGN_VILLAIN = 6
const ALIGN_TERRIBLE = 7
const ALIGN_HORRIBLE = 8
const NUM_ALIGNS = 9
const SIZE_UNDEFINED = -1
const SIZE_FINE = 0
const SIZE_DIMINUTIVE = 1
const SIZE_TINY = 2
const SIZE_SMALL = 3
const SIZE_MEDIUM = 4
const SIZE_LARGE = 5
const SIZE_HUGE = 6
const SIZE_GARGANTUAN = 7
const SIZE_COLOSSAL = 8
const NUM_SIZES = 9
const WIELD_NONE = 0
const WIELD_LIGHT = 1
const WIELD_ONEHAND = 2
const WIELD_TWOHAND = 3
const MAX_WEAPON_TYPES = 26
const CRIT_X2 = 0
const CRIT_X3 = 1
const CRIT_X4 = 2
const MAX_CRIT_TYPE = 2
const NUM_CRIT_TYPES = 3
const SEX_NEUTRAL = 0
const SEX_MALE = 1
const SEX_FEMALE = 2
const NUM_SEX = 3
const POS_DEAD = 0
const POS_MORTALLYW = 1
const POS_INCAP = 2
const POS_STUNNED = 3
const POS_SLEEPING = 4
const POS_RESTING = 5
const POS_SITTING = 6
const POS_FIGHTING = 7
const POS_STANDING = 8
const NUM_POSITIONS = 9
const AUC_NULL_STATE = 0
const AUC_OFFERING = 1
const AUC_GOING_ONCE = 2
const AUC_GOING_TWICE = 3
const AUC_LAST_CALL = 4
const AUC_SOLD = 5
const AUC_NORMAL_CANCEL = 6
const AUC_QUIT_CANCEL = 7
const AUC_WIZ_CANCEL = 8
const AUC_STAT = 9
const AUC_BID = 10
const PLR_KILLER = 0
const PLR_THIEF = 1
const PLR_FROZEN = 2
const PLR_DONTSET = 3
const PLR_WRITING = 4
const PLR_MAILING = 5
const PLR_CRASH = 6
const PLR_SITEOK = 7
const PLR_NOSHOUT = 8
const PLR_NOTITLE = 9
const PLR_DELETED = 10
const PLR_LOADROOM = 11
const PLR_NOWIZLIST = 12
const PLR_NODELETE = 13
const PLR_INVSTART = 14
const PLR_CRYO = 15
const PLR_NOTDEADYET = 16
const PLR_AGEMID_G = 17
const PLR_AGEMID_B = 18
const PLR_AGEOLD_G = 19
const PLR_AGEOLD_B = 20
const PLR_AGEVEN_G = 21
const PLR_AGEVEN_B = 22
const PLR_OLDAGE = 23
const PLR_RARM = 24
const PLR_LARM = 25
const PLR_RLEG = 26
const PLR_LLEG = 27
const PLR_HEAD = 28
const PLR_STAIL = 29
const PLR_TAIL = 30
const PLR_PILOTING = 31
const PLR_SKILLP = 32
const PLR_SPAR = 33
const PLR_CHARGE = 34
const PLR_TRANS1 = 35
const PLR_TRANS2 = 36
const PLR_TRANS3 = 37
const PLR_TRANS4 = 38
const PLR_TRANS5 = 39
const PLR_TRANS6 = 40
const PLR_ABSORB = 41
const PLR_REPAIR = 42
const PLR_SENSEM = 43
const PLR_POWERUP = 44
const PLR_KNOCKED = 45
const PLR_CRARM = 46
const PLR_CLARM = 47
const PLR_CRLEG = 48
const PLR_CLLEG = 49
const PLR_FPSSJ = 50
const PLR_IMMORTAL = 51
const PLR_EYEC = 52
const PLR_DISGUISED = 53
const PLR_BANDAGED = 54
const PLR_PR = 55
const PLR_HEALT = 56
const PLR_FURY = 57
const PLR_POSE = 58
const PLR_OOZARU = 59
const PLR_ABSORBED = 60
const PLR_MULTP = 61
const PLR_PDEATH = 62
const PLR_THANDW = 63
const PLR_SELFD = 64
const PLR_SELFD2 = 65
const PLR_SPIRAL = 66
const PLR_BIOGR = 67
const PLR_LSSJ = 68
const PLR_REPLEARN = 69
const PLR_FORGET = 70
const PLR_TRANSMISSION = 71
const PLR_FISHING = 72
const PLR_GOOP = 73
const PLR_MULTIHIT = 74
const PLR_AURALIGHT = 75
const PLR_RDISPLAY = 76
const PLR_STOLEN = 77
const PLR_TAILHIDE = 78
const PLR_NOGROW = 79
const NUM_PLR_FLAGS = 80
const MAX_PERSONALITIES = 5
const MOB_SPEC = 0
const MOB_SENTINEL = 1
const MOB_NOSCAVENGER = 2
const MOB_ISNPC = 3
const MOB_AWARE = 4
const MOB_AGGRESSIVE = 5
const MOB_STAY_ZONE = 6
const MOB_WIMPY = 7
const MOB_AGGR_EVIL = 8
const MOB_AGGR_GOOD = 9
const MOB_AGGR_NEUTRAL = 10
const MOB_MEMORY = 11
const MOB_HELPER = 12
const MOB_NOCHARM = 13
const MOB_NOSUMMON = 14
const MOB_NOSLEEP = 15
const MOB_AUTOBALANCE = 16
const MOB_NOBLIND = 17
const MOB_NOKILL = 18
const MOB_NOTDEADYET = 19
const MOB_MOUNTABLE = 20
const MOB_RARM = 21
const MOB_LARM = 22
const MOB_RLEG = 23
const MOB_LLEG = 24
const MOB_HEAD = 25
const MOB_JUSTDESC = 26
const MOB_HUSK = 27
const MOB_SPAR = 28
const MOB_DUMMY = 29
const MOB_ABSORB = 30
const MOB_REPAIR = 31
const MOB_NOPOISON = 32
const MOB_KNOWKAIO = 33
const MOB_POWERUP = 34
const NUM_MOB_FLAGS = 35
const PRF_BRIEF = 0
const PRF_COMPACT = 1
const PRF_DEAF = 2
const PRF_NOTELL = 3
const PRF_DISPHP = 4
const PRF_DISPMANA = 5
const PRF_DISPMOVE = 6
const PRF_AUTOEXIT = 7
const PRF_NOHASSLE = 8
const PRF_QUEST = 9
const PRF_SUMMONABLE = 10
const PRF_NOREPEAT = 11
const PRF_HOLYLIGHT = 12
const PRF_COLOR = 13
const PRF_SPARE = 14
const PRF_NOWIZ = 15
const PRF_LOG1 = 16
const PRF_LOG2 = 17
const PRF_NOAUCT = 18
const PRF_NOGOSS = 19
const PRF_NOGRATZ = 20
const PRF_ROOMFLAGS = 21
const PRF_DISPAUTO = 22
const PRF_CLS = 23
const PRF_BUILDWALK = 24
const PRF_AFK = 25
const PRF_AUTOLOOT = 26
const PRF_AUTOGOLD = 27
const PRF_AUTOSPLIT = 28
const PRF_FULL_EXIT = 29
const PRF_AUTOSAC = 30
const PRF_AUTOMEM = 31
const PRF_VIEWORDER = 32
const PRF_NOCOMPRESS = 33
const PRF_AUTOASSIST = 34
const PRF_DISPKI = 35
const PRF_DISPEXP = 36
const PRF_DISPTNL = 37
const PRF_TEST = 38
const PRF_HIDE = 39
const PRF_NMWARN = 40
const PRF_HINTS = 41
const PRF_FURY = 42
const PRF_NODEC = 43
const PRF_NOEQSEE = 44
const PRF_NOMUSIC = 45
const PRF_LKEEP = 46
const PRF_DISTIME = 47
const PRF_DISGOLD = 48
const PRF_DISPRAC = 49
const PRF_NOPARRY = 50
const PRF_DISHUTH = 51
const PRF_DISPERC = 52
const PRF_CARVE = 53
const PRF_ARENAWATCH = 54
const PRF_NOGIVE = 55
const PRF_INSTRUCT = 56
const PRF_GHEALTH = 57
const PRF_IHEALTH = 58
const PRF_ENERGIZE = 59
const NUM_PRF_FLAGS = 60
const EXIT_OFF = 0
const EXIT_NORMAL = 1
const EXIT_NA = 2
const EXIT_COMPLETE = 3
const AFF_DONTUSE = 0
const AFF_BLIND = 1
const AFF_INVISIBLE = 2
const AFF_DETECT_ALIGN = 3
const AFF_DETECT_INVIS = 4
const AFF_DETECT_MAGIC = 5
const AFF_SENSE_LIFE = 6
const AFF_WATERWALK = 7
const AFF_SANCTUARY = 8
const AFF_GROUP = 9
const AFF_CURSE = 10
const AFF_INFRAVISION = 11
const AFF_POISON = 12
const AFF_WEAKENED_STATE = 13
const AFF_PROTECT_GOOD = 14
const AFF_SLEEP = 15
const AFF_NOTRACK = 16
const AFF_UNDEAD = 17
const AFF_PARALYZE = 18
const AFF_SNEAK = 19
const AFF_HIDE = 20
const AFF_UNUSED20 = 21
const AFF_CHARM = 22
const AFF_FLYING = 23
const AFF_WATERBREATH = 24
const AFF_ANGELIC = 25
const AFF_ETHEREAL = 26
const AFF_MAGICONLY = 27
const AFF_NEXTPARTIAL = 28
const AFF_NEXTNOACTION = 29
const AFF_STUNNED = 30
const AFF_TAMED = 31
const AFF_CDEATH = 32
const AFF_SPIRIT = 33
const AFF_STONESKIN = 34
const AFF_SUMMONED = 35
const AFF_CELESTIAL = 36
const AFF_FIENDISH = 37
const AFF_FIRE_SHIELD = 38
const AFF_LOW_LIGHT = 39
const AFF_ZANZOKEN = 40
const AFF_KNOCKED = 41
const AFF_MIGHT = 42
const AFF_FLEX = 43
const AFF_GENIUS = 44
const AFF_BLESS = 45
const AFF_BURNT = 46
const AFF_BURNED = 47
const AFF_MBREAK = 48
const AFF_HASS = 49
const AFF_FUTURE = 50
const AFF_PARA = 51
const AFF_INFUSE = 52
const AFF_ENLIGHTEN = 53
const AFF_FROZEN = 54
const AFF_FIRESHIELD = 55
const AFF_ENSNARED = 56
const AFF_HAYASA = 57
const AFF_PURSUIT = 58
const AFF_WITHER = 59
const AFF_HYDROZAP = 60
const AFF_POSITION = 61
const AFF_SHOCKED = 62
const AFF_METAMORPH = 63
const AFF_HEALGLOW = 64
const AFF_EARMOR = 65
const AFF_ECHAINS = 66
const AFF_WUNJO = 67
const AFF_POTENT = 68
const AFF_ASHED = 69
const AFF_PUKED = 70
const AFF_LIQUEFIED = 71
const AFF_SHELL = 72
const AFF_IMMUNITY = 73
const AFF_SPIRITCONTROL = 74
const NUM_AFF_FLAGS = 75
const CON_PLAYING = 0
const CON_CLOSE = 1
const CON_GET_NAME = 2
const CON_NAME_CNFRM = 3
const CON_PASSWORD = 4
const CON_NEWPASSWD = 5
const CON_CNFPASSWD = 6
const CON_QSEX = 7
const CON_QCLASS = 8
const CON_RMOTD = 9
const CON_MENU = 10
const CON_EXDESC = 11
const CON_CHPWD_GETOLD = 12
const CON_CHPWD_GETNEW = 13
const CON_CHPWD_VRFY = 14
const CON_DELCNF1 = 15
const CON_DELCNF2 = 16
const CON_DISCONNECT = 17
const CON_OEDIT = 18
const CON_REDIT = 19
const CON_ZEDIT = 20
const CON_MEDIT = 21
const CON_SEDIT = 22
const CON_TEDIT = 23
const CON_CEDIT = 24
const CON_QRACE = 25
const CON_ASSEDIT = 26
const CON_AEDIT = 27
const CON_TRIGEDIT = 28
const CON_RACE_HELP = 29
const CON_CLASS_HELP = 30
const CON_QANSI = 31
const CON_GEDIT = 32
const CON_QROLLSTATS = 33
const CON_IEDIT = 34
const CON_LEVELUP = 35
const CON_QSTATS = 36
const CON_HAIRL = 37
const CON_HAIRS = 38
const CON_HAIRC = 39
const CON_SKIN = 40
const CON_EYE = 41
const CON_Q1 = 42
const CON_Q2 = 43
const CON_Q3 = 44
const CON_Q4 = 45
const CON_Q5 = 46
const CON_Q6 = 47
const CON_Q7 = 48
const CON_Q8 = 49
const CON_Q9 = 50
const CON_QX = 51
const CON_HSEDIT = 52
const CON_ALPHA = 53
const CON_ALPHA2 = 54
const CON_ANDROID = 55
const CON_HEDIT = 56
const CON_GET_USER = 57
const CON_GET_EMAIL = 58
const CON_UMENU = 59
const CON_USER_CONF = 60
const CON_DISTFEA = 61
const CON_HW = 62
const CON_AURA = 63
const CON_BONUS = 64
const CON_NEGATIVE = 65
const CON_NEWSEDIT = 66
const CON_RACIAL = 67
const CON_POBJ = 68
const CON_ALIGN = 69
const CON_SKILLS = 70
const CON_USER_TITLE = 71
const CON_GENOME = 72
const NUM_CON_TYPES = 73
const COLOR_NORMAL = 0
const COLOR_ROOMNAME = 1
const COLOR_ROOMOBJS = 2
const COLOR_ROOMPEOPLE = 3
const COLOR_HITYOU = 4
const COLOR_YOUHIT = 5
const COLOR_OTHERHIT = 6
const COLOR_CRITICAL = 7
const COLOR_HOLLER = 8
const COLOR_SHOUT = 9
const COLOR_GOSSIP = 10
const COLOR_AUCTION = 11
const COLOR_CONGRAT = 12
const COLOR_TELL = 13
const COLOR_YOUSAY = 14
const COLOR_ROOMSAY = 15
const NUM_COLOR = 16
const WEAR_UNUSED0 = 0
const WEAR_FINGER_R = 1
const WEAR_FINGER_L = 2
const WEAR_NECK_1 = 3
const WEAR_NECK_2 = 4
const WEAR_BODY = 5
const WEAR_HEAD = 6
const WEAR_LEGS = 7
const WEAR_FEET = 8
const WEAR_HANDS = 9
const WEAR_ARMS = 10
const WEAR_UNUSED1 = 11
const WEAR_ABOUT = 12
const WEAR_WAIST = 13
const WEAR_WRIST_R = 14
const WEAR_WRIST_L = 15
const WEAR_WIELD1 = 16
const WEAR_WIELD2 = 17
const WEAR_BACKPACK = 18
const WEAR_EAR_R = 19
const WEAR_EAR_L = 20
const WEAR_SH = 21
const WEAR_EYE = 22
const NUM_WEARS = 23
const SPELL_LEVEL_0 = 0
const SPELL_LEVEL_1 = 1
const SPELL_LEVEL_2 = 2
const SPELL_LEVEL_3 = 3
const SPELL_LEVEL_4 = 4
const SPELL_LEVEL_5 = 5
const SPELL_LEVEL_6 = 6
const SPELL_LEVEL_7 = 7
const SPELL_LEVEL_8 = 8
const SPELL_LEVEL_9 = 9
const MAX_SPELL_LEVEL = 10
const MAX_MEM = 100
const DOMAIN_UNDEFINED = -1
const DOMAIN_AIR = 0
const DOMAIN_ANIMAL = 1
const DOMAIN_CHAOS = 2
const DOMAIN_DEATH = 3
const DOMAIN_DESTRUCTION = 4
const DOMAIN_EARTH = 5
const DOMAIN_EVIL = 6
const DOMAIN_FIRE = 7
const DOMAIN_GOOD = 8
const DOMAIN_HEALING = 9
const DOMAIN_KNOWLEDGE = 10
const DOMAIN_LAW = 11
const DOMAIN_LUCK = 12
const DOMAIN_MAGIC = 13
const DOMAIN_PLANT = 14
const DOMAIN_PROTECTION = 15
const DOMAIN_STRENGTH = 16
const DOMAIN_SUN = 17
const DOMAIN_TRAVEL = 18
const DOMAIN_TRICKERY = 19
const DOMAIN_UNIVERSAL = 20
const DOMAIN_WAR = 22
const DOMAIN_WATER = 23
const DOMAIN_ARTIFACE = 24
const DOMAIN_CHARM = 25
const DOMAIN_COMMUNITY = 26
const DOMAIN_CREATION = 27
const DOMAIN_DARKNESS = 28
const DOMAIN_GLORY = 29
const DOMAIN_LIBERATION = 30
const DOMAIN_MADNESS = 31
const DOMAIN_NOBILITY = 32
const DOMAIN_REPOSE = 33
const DOMAIN_RUNE = 34
const DOMAIN_SCALYKIND = 35
const DOMAIN_WEATHER = 36
const NUM_DOMAINS = 37
const SCHOOL_UNDEFINED = -1
const SCHOOL_ABJURATION = 0
const SCHOOL_CONJURATION = 1
const SCHOOL_DIVINATION = 2
const SCHOOL_ENCHANTMENT = 3
const SCHOOL_EVOCATION = 4
const SCHOOL_ILLUSION = 5
const SCHOOL_NECROMANCY = 6
const SCHOOL_TRANSMUTATION = 7
const SCHOOL_UNIVERSAL = 8
const NUM_SCHOOLS = 10
const DEITY_UNDEFINED = -1
const NUM_DEITIES = 0
const CFEAT_IMPROVED_CRITICAL = 0
const CFEAT_WEAPON_FINESSE = 1
const CFEAT_WEAPON_FOCUS = 2
const CFEAT_WEAPON_SPECIALIZATION = 3
const CFEAT_GREATER_WEAPON_FOCUS = 4
const CFEAT_GREATER_WEAPON_SPECIALIZATION = 5
const CFEAT_MAX = 5
const CFEAT_SPELL_FOCUS = 0
const CFEAT_GREATER_SPELL_FOCUS = 1
const SFEAT_MAX = 1
const ITEM_LIGHT = 1
const ITEM_SCROLL = 2
const ITEM_WAND = 3
const ITEM_STAFF = 4
const ITEM_WEAPON = 5
const ITEM_FIREWEAPON = 6
const ITEM_CAMPFIRE = 7
const ITEM_TREASURE = 8
const ITEM_ARMOR = 9
const ITEM_POTION = 10
const ITEM_WORN = 11
const ITEM_OTHER = 12
const ITEM_TRASH = 13
const ITEM_TRAP = 14
const ITEM_CONTAINER = 15
const ITEM_NOTE = 16
const ITEM_DRINKCON = 17
const ITEM_KEY = 18
const ITEM_FOOD = 19
const ITEM_MONEY = 20
const ITEM_PEN = 21
const ITEM_BOAT = 22
const ITEM_FOUNTAIN = 23
const ITEM_VEHICLE = 24
const ITEM_HATCH = 25
const ITEM_WINDOW = 26
const ITEM_CONTROL = 27
const ITEM_PORTAL = 28
const ITEM_SPELLBOOK = 29
const ITEM_BOARD = 30
const ITEM_CHAIR = 31
const ITEM_BED = 32
const ITEM_YUM = 33
const ITEM_PLANT = 34
const ITEM_FISHPOLE = 35
const ITEM_FISHBAIT = 36
const NUM_ITEM_TYPES = 37
const ITEM_WEAR_TAKE = 0
const ITEM_WEAR_FINGER = 1
const ITEM_WEAR_NECK = 2
const ITEM_WEAR_BODY = 3
const ITEM_WEAR_HEAD = 4
const ITEM_WEAR_LEGS = 5
const ITEM_WEAR_FEET = 6
const ITEM_WEAR_HANDS = 7
const ITEM_WEAR_ARMS = 8
const ITEM_WEAR_SHIELD = 9
const ITEM_WEAR_ABOUT = 10
const ITEM_WEAR_WAIST = 11
const ITEM_WEAR_WRIST = 12
const ITEM_WEAR_WIELD = 13
const ITEM_WEAR_HOLD = 14
const ITEM_WEAR_PACK = 15
const ITEM_WEAR_EAR = 16
const ITEM_WEAR_SH = 17
const ITEM_WEAR_EYE = 18
const NUM_ITEM_WEARS = 19
const ITEM_GLOW = 0
const ITEM_HUM = 1
const ITEM_NORENT = 2
const ITEM_NODONATE = 3
const ITEM_NOINVIS = 4
const ITEM_INVISIBLE = 5
const ITEM_MAGIC = 6
const ITEM_NODROP = 7
const ITEM_BLESS = 8
const ITEM_ANTI_GOOD = 9
const ITEM_ANTI_EVIL = 10
const ITEM_ANTI_NEUTRAL = 11
const ITEM_ANTI_WIZARD = 12
const ITEM_ANTI_CLERIC = 13
const ITEM_ANTI_ROGUE = 14
const ITEM_ANTI_FIGHTER = 15
const ITEM_NOSELL = 16
const ITEM_ANTI_DRUID = 17
const ITEM_2H = 18
const ITEM_ANTI_BARD = 19
const ITEM_ANTI_RANGER = 20
const ITEM_ANTI_PALADIN = 21
const ITEM_ANTI_HUMAN = 22
const ITEM_ANTI_ICER = 23
const ITEM_ANTI_SAIYAN = 24
const ITEM_ANTI_KONATSU = 25
const ITEM_UNIQUE_SAVE = 26
const ITEM_BROKEN = 27
const ITEM_UNBREAKABLE = 28
const ITEM_ANTI_MONK = 29
const ITEM_ANTI_BARBARIAN = 30
const ITEM_ANTI_SORCERER = 31
const ITEM_DOUBLE = 32
const ITEM_ONLY_WIZARD = 33
const ITEM_ONLY_CLERIC = 34
const ITEM_ONLY_ROGUE = 35
const ITEM_ONLY_FIGHTER = 36
const ITEM_ONLY_DRUID = 37
const ITEM_ONLY_BARD = 38
const ITEM_ONLY_RANGER = 39
const ITEM_ONLY_PALADIN = 40
const ITEM_ONLY_HUMAN = 41
const ITEM_ONLY_ICER = 42
const ITEM_ONLY_SAIYAN = 43
const ITEM_ONLY_KONATSU = 44
const ITEM_ONLY_MONK = 45
const ITEM_ONLY_BARBARIAN = 46
const ITEM_ONLY_SORCERER = 47
const ITEM_ANTI_ARCANE_ARCHER = 48
const ITEM_ANTI_ARCANE_TRICKSTER = 49
const ITEM_ANTI_ARCHMAGE = 50
const ITEM_ANTI_ASSASSIN = 51
const ITEM_ANTI_BLACKGUARD = 52
const ITEM_ANTI_DRAGON_DISCIPLE = 53
const ITEM_ANTI_DUELIST = 54
const ITEM_ANTI_DWARVEN_DEFENDER = 55
const ITEM_ANTI_ELDRITCH_KNIGHT = 56
const ITEM_ANTI_HIEROPHANT = 57
const ITEM_ANTI_HORIZON_WALKER = 58
const ITEM_ANTI_LOREMASTER = 59
const ITEM_ANTI_MYSTIC_THEURGE = 60
const ITEM_ANTI_SHADOWDANCER = 61
const ITEM_ANTI_THAUMATURGIST = 62
const ITEM_BSCOUTER = 63
const ITEM_MSCOUTER = 64
const ITEM_ASCOUTER = 65
const ITEM_USCOUTER = 66
const ITEM_WEAPLVL1 = 67
const ITEM_WEAPLVL2 = 68
const ITEM_WEAPLVL3 = 69
const ITEM_WEAPLVL4 = 70
const ITEM_WEAPLVL5 = 71
const ITEM_CBOARD = 72
const ITEM_FORGED = 73
const ITEM_SHEATH = 74
const ITEM_ONLY_JINTO = 75
const ITEM_BURIED = 76
const ITEM_SLOT1 = 77
const ITEM_SLOT2 = 78
const ITEM_TOKEN = 79
const ITEM_SLOT_ONE = 80
const ITEM_SLOTS_FILLED = 81
const ITEM_RESTRING = 82
const ITEM_CUSTOM = 83
const ITEM_PROTECTED = 84
const ITEM_NORANDOM = 85
const ITEM_THROW = 86
const ITEM_HOT = 87
const ITEM_PURGE = 88
const ITEM_ICE = 89
const ITEM_DUPLICATE = 90
const ITEM_MATURE = 91
const ITEM_CARDCASE = 92
const ITEM_NOPICKUP = 93
const ITEM_NOSTEAL = 94
const NUM_ITEM_FLAGS = 95
const APPLY_NONE = 0
const APPLY_STR = 1
const APPLY_DEX = 2
const APPLY_INT = 3
const APPLY_WIS = 4
const APPLY_CON = 5
const APPLY_CHA = 6
const APPLY_CLASS = 7
const APPLY_LEVEL = 8
const APPLY_AGE = 9
const APPLY_CHAR_WEIGHT = 10
const APPLY_CHAR_HEIGHT = 11
const APPLY_MANA = 12
const APPLY_HIT = 13
const APPLY_MOVE = 14
const APPLY_GOLD = 15
const APPLY_EXP = 16
const APPLY_AC = 17
const APPLY_ACCURACY = 18
const APPLY_DAMAGE = 19
const APPLY_REGEN = 20
const APPLY_TRAIN = 21
const APPLY_LIFEMAX = 22
const APPLY_UNUSED3 = 23
const APPLY_UNUSED4 = 24
const APPLY_RACE = 25
const APPLY_TURN_LEVEL = 26
const APPLY_SPELL_LVL_0 = 27
const APPLY_SPELL_LVL_1 = 28
const APPLY_SPELL_LVL_2 = 29
const APPLY_SPELL_LVL_3 = 30
const APPLY_SPELL_LVL_4 = 31
const APPLY_SPELL_LVL_5 = 32
const APPLY_SPELL_LVL_6 = 33
const APPLY_SPELL_LVL_7 = 34
const APPLY_SPELL_LVL_8 = 35
const APPLY_SPELL_LVL_9 = 36
const APPLY_KI = 37
const APPLY_FORTITUDE = 38
const APPLY_REFLEX = 39
const APPLY_WILL = 40
const APPLY_SKILL = 41
const APPLY_FEAT = 42
const APPLY_ALLSAVES = 43
const APPLY_RESISTANCE = 44
const APPLY_ALL_STATS = 45
const NUM_APPLIES = 46
const CONT_CLOSEABLE = 1
const CONT_PICKPROOF = 2
const CONT_CLOSED = 4
const CONT_LOCKED = 8
const NUM_CONT_FLAGS = 4
const LIQ_WATER = 0
const LIQ_BEER = 1
const LIQ_WINE = 2
const LIQ_ALE = 3
const LIQ_DARKALE = 4
const LIQ_WHISKY = 5
const LIQ_LEMONADE = 6
const LIQ_FIREBRT = 7
const LIQ_LOCALSPC = 8
const LIQ_SLIME = 9
const LIQ_MILK = 10
const LIQ_TEA = 11
const LIQ_COFFE = 12
const LIQ_BLOOD = 13
const LIQ_SALTWATER = 14
const LIQ_CLEARWATER = 15
const NUM_LIQ_TYPES = 16
const MATERIAL_BONE = 0
const MATERIAL_CERAMIC = 1
const MATERIAL_COPPER = 2
const MATERIAL_DIAMOND = 3
const MATERIAL_GOLD = 4
const MATERIAL_IRON = 5
const MATERIAL_LEATHER = 6
const MATERIAL_MITHRIL = 7
const MATERIAL_OBSIDIAN = 8
const MATERIAL_STEEL = 9
const MATERIAL_STONE = 10
const MATERIAL_SILVER = 11
const MATERIAL_WOOD = 12
const MATERIAL_GLASS = 13
const MATERIAL_ORGANIC = 14
const MATERIAL_CURRENCY = 15
const MATERIAL_PAPER = 16
const MATERIAL_COTTON = 17
const MATERIAL_SATIN = 18
const MATERIAL_SILK = 19
const MATERIAL_BURLAP = 20
const MATERIAL_VELVET = 21
const MATERIAL_PLATINUM = 22
const MATERIAL_ADAMANTINE = 23
const MATERIAL_WOOL = 24
const MATERIAL_ONYX = 25
const MATERIAL_IVORY = 26
const MATERIAL_BRASS = 27
const MATERIAL_MARBLE = 28
const MATERIAL_BRONZE = 29
const MATERIAL_KACHIN = 30
const MATERIAL_RUBY = 31
const MATERIAL_SAPPHIRE = 32
const MATERIAL_EMERALD = 33
const MATERIAL_GEMSTONE = 34
const MATERIAL_GRANITE = 35
const MATERIAL_ENERGY = 36
const MATERIAL_HEMP = 37
const MATERIAL_CRYSTAL = 38
const MATERIAL_EARTH = 39
const MATERIAL_LIQUID = 40
const MATERIAL_CLOTH = 41
const MATERIAL_METAL = 42
const MATERIAL_WAX = 43
const MATERIAL_OTHER = 44
const MATERIAL_FOOD = 45
const MATERIAL_OIL = 46
const NUM_MATERIALS = 47
const DRUNK = 0
const HUNGER = 1
const THIRST = 2
const SUN_DARK = 0
const SUN_RISE = 1
const SUN_LIGHT = 2
const SUN_SET = 3
const SKY_CLOUDLESS = 0
const SKY_CLOUDY = 1
const SKY_RAINING = 2
const SKY_LIGHTNING = 3
const RENT_UNDEF = 0
const RENT_CRASH = 1
const RENT_RENTED = 2
const RENT_CRYO = 3
const RENT_FORCED = 4
const RENT_TIMEDOUT = 5
const RF_ARRAY_MAX = 4
const PM_ARRAY_MAX = 4
const PR_ARRAY_MAX = 4
const AF_ARRAY_MAX = 4
const TW_ARRAY_MAX = 4
const EF_ARRAY_MAX = 4
const AD_ARRAY_MAX = 4
const FT_ARRAY_MAX = 4
const ZF_ARRAY_MAX = 4
const HIST_ALL = 0
const HIST_SAY = 1
const HIST_GOSSIP = 2
const HIST_WIZNET = 3
const HIST_TELL = 4
const HIST_SHOUT = 5
const HIST_GRATS = 6
const HIST_HOLLER = 7
const HIST_AUCTION = 8
const HIST_SNET = 9
const NUM_HIST = 10
const ADMLVL_NONE = 0
const ADMLVL_IMMORT = 1
const ADMLVL_BUILDER = 2
const ADMLVL_GOD = 3
const ADMLVL_VICE = 4
const ADMLVL_GRGOD = 5
const ADMLVL_IMPL = 6
const LVL_EPICSTART = 101
const ADM_TELLALL = 0
const ADM_SEEINV = 1
const ADM_SEESECRET = 2
const ADM_KNOWWEATHER = 3
const ADM_FULLWHERE = 4
const ADM_MONEY = 5
const ADM_EATANYTHING = 6
const ADM_NOPOISON = 7
const ADM_WALKANYWHERE = 8
const ADM_NOKEYS = 9
const ADM_INSTANTKILL = 10
const ADM_NOSTEAL = 11
const ADM_TRANSALL = 12
const ADM_SWITCHMORTAL = 13
const ADM_FORCEMASS = 14
const ADM_ALLHOUSES = 15
const ADM_NODAMAGE = 16
const ADM_ALLSHOPS = 17
const ADM_CEDIT = 18
const NUM_ADMFLAGS = 19
const ADMLVL_FREEZE = 5
const NUM_OF_DIRS = 12
const OPT_USEC = 100000
const PASSES_PER_SEC = 10
const RL_SEC = 0
const CD_TICK = 0
const PULSE_AUCTION = 150
const PULSE_1SEC = 10
const PULSE_2SEC = 20
const PULSE_3SEC = 30
const PULSE_4SEC = 40
const PULSE_5SEC = 50
const PULSE_6SEC = 60
const PULSE_7SEC = 70
const PULSE_CD1 = 10
const PULSE_CD2 = 20
const PULSE_CD3 = 30
const PULSE_CD4 = 40
const PULSE_CD5 = 50
const PULSE_CD6 = 60
const PULSE_CD7 = 70
const PULSE_CD8 = 80
const PULSE_CD9 = 90
const PULSE_CD10 = 100
const PULSE_CD11 = 110
const PULSE_CD12 = 120
const MAX_SOCK_BUF = 0x18000
const MAX_PROMPT_LENGTH = 1024
const GARBAGE_SPACE = 512
const SMALL_BUFSIZE = 6020
const LARGE_BUFSIZE = 0x17A00
const HISTORY_SIZE = 5
const MAX_STRING_LENGTH = 0xFDA8
const MAX_INPUT_LENGTH = 2048
const MAX_RAW_INPUT_LENGTH = 4096
const MAX_MESSAGES = 100
const MAX_NAME_LENGTH = 20
const MAX_PWD_LENGTH = 30
const MAX_TITLE_LENGTH = 120
const HOST_LENGTH = 40
const EXDSCR_LENGTH = 0x4000
const MAX_TONGUE = 3
const MAX_SKILLS = 200
const MAX_AFFECT = 32
const MAX_OBJ_AFFECT = 6
const MAX_NOTE_LENGTH = 6000
const SKILL_TABLE_SIZE = 1000
const SPELLBOOK_SIZE = 50
const MAX_FEATS = 750
const MAX_HELP_KEYWORDS = 256
const MAX_HELP_ENTRY = 0xFDA8
const NUM_FEATS_DEFINED = 252
const MAX_ARMOR_TYPES = 5
const NUM_CONFIG_SECTIONS = 7
const NUM_CREATION_METHODS = 5
const NUM_ATTACK_TYPES = 15
const NUM_MTRIG_TYPES = 20
const NUM_OTRIG_TYPES = 20
const NUM_WTRIG_TYPES = 20
const NUM_ZONE_FLAGS = 36
const NUM_TRADERS = 78
const NUM_SHOP_FLAGS = 3
const NUM_DOOR_CMD = 5
const MAX_ASSM = 11
const NUM_FULLNESS = 5
const NUM_WEEK_DAYS = 7
const NUM_MONTHS = 12
const NUM_CONDITIONS = 3
const NUM_WIELD_NAMES = 4
const MAX_CMD_LENGTH = 0x4000
const NUM_OBJ_VAL_POSITIONS = 16
const VAL_ALL_HEALTH = 4
const VAL_ALL_MAXHEALTH = 5
const VAL_ALL_MATERIAL = 7
const VAL_LIGHT_TIME = 0
const VAL_LIGHT_UNUSED2 = 1
const VAL_LIGHT_HOURS = 2
const VAL_LIGHT_UNUSED4 = 3
const VAL_LIGHT_HEALTH = 4
const VAL_LIGHT_MAXHEALTH = 5
const VAL_LIGHT_UNUSED7 = 6
const VAL_LIGHT_MATERIAL = 7
const VAL_SCROLL_LEVEL = 0
const VAL_SCROLL_SPELL1 = 1
const VAL_SCROLL_SPELL2 = 2
const VAL_SCROLL_SPELL3 = 3
const VAL_SCROLL_HEALTH = 4
const VAL_SCROLL_MAXHEALTH = 5
const VAL_SCROLL_UNUSED7 = 6
const VAL_SCROLL_MATERIAL = 7
const VAL_WAND_LEVEL = 0
const VAL_WAND_MAXCHARGES = 1
const VAL_WAND_CHARGES = 2
const VAL_WAND_SPELL = 3
const VAL_WAND_HEALTH = 4
const VAL_WAND_MAXHEALTH = 5
const VAL_WAND_UNUSED7 = 6
const VAL_WAND_MATERIAL = 7
const VAL_STAFF_LEVEL = 0
const VAL_STAFF_MAXCHARGES = 1
const VAL_STAFF_CHARGES = 2
const VAL_STAFF_SPELL = 3
const VAL_STAFF_HEALTH = 4
const VAL_STAFF_MAXHEALTH = 5
const VAL_STAFF_UNUSED7 = 6
const VAL_STAFF_MATERIAL = 7
const VAL_WEAPON_SKILL = 0
const VAL_WEAPON_DAMDICE = 1
const VAL_WEAPON_DAMSIZE = 2
const VAL_WEAPON_DAMTYPE = 3
const VAL_WEAPON_HEALTH = 4
const VAL_WEAPON_MAXHEALTH = 5
const VAL_WEAPON_CRITTYPE = 6
const VAL_WEAPON_MATERIAL = 7
const VAL_WEAPON_CRITRANGE = 8
const VAL_FIREWEAPON_UNUSED1 = 0
const VAL_FIREWEAPON_UNUSED2 = 1
const VAL_FIREWEAPON_UNUSED3 = 2
const VAL_FIREWEAPON_UNUSED4 = 3
const VAL_FIREWEAPON_HEALTH = 4
const VAL_FIREWEAPON_MAXHEALTH = 5
const VAL_FIREWEAPON_UNUSED7 = 6
const VAL_FIREWEAPON_MATERIAL = 7
const VAL_MISSILE_UNUSED1 = 0
const VAL_MISSILE_UNUSED2 = 1
const VAL_MISSILE_UNUSED3 = 2
const VAL_MISSILE_UNUSED4 = 3
const VAL_MISSILE_HEALTH = 4
const VAL_MISSILE_MAXHEALTH = 5
const VAL_MISSILE_UNUSED7 = 6
const VAL_MISSILE_MATERIAL = 7
const VAL_TREASURE_UNUSED1 = 0
const VAL_TREASURE_UNUSED2 = 1
const VAL_TREASURE_UNUSED3 = 2
const VAL_TREASURE_UNUSED4 = 3
const VAL_TREASURE_HEALTH = 4
const VAL_TREASURE_MAXHEALTH = 5
const VAL_TREASURE_UNUSED7 = 6
const VAL_TREASURE_MATERIAL = 7
const VAL_ARMOR_APPLYAC = 0
const VAL_ARMOR_SKILL = 1
const VAL_ARMOR_MAXDEXMOD = 2
const VAL_ARMOR_CHECK = 3
const VAL_ARMOR_HEALTH = 4
const VAL_ARMOR_MAXHEALTH = 5
const VAL_ARMOR_SPELLFAIL = 6
const VAL_ARMOR_MATERIAL = 7
const VAL_POTION_LEVEL = 0
const VAL_POTION_SPELL1 = 1
const VAL_POTION_SPELL2 = 2
const VAL_POTION_SPELL3 = 3
const VAL_POTION_HEALTH = 4
const VAL_POTION_MAXHEALTH = 5
const VAL_POTION_UNUSED7 = 6
const VAL_POTION_MATERIAL = 7
const VAL_WORN_UNUSED1 = 0
const VAL_WORN_UNUSED2 = 1
const VAL_WORN_UNUSED3 = 2
const VAL_WORN_UNUSED4 = 3
const VAL_WORN_HEALTH = 4
const VAL_WORN_MAXHEALTH = 5
const VAL_WORN_UNUSED7 = 6
const VAL_WORN_MATERIAL = 7
const VAL_OTHER_UNUSED1 = 0
const VAL_OTHER_UNUSED2 = 1
const VAL_OTHER_UNUSED3 = 2
const VAL_OTHER_UNUSED4 = 3
const VAL_OTHER_HEALTH = 4
const VAL_OTHER_MAXHEALTH = 5
const VAL_OTHER_UNUSED7 = 6
const VAL_OTHER_MATERIAL = 7
const VAL_TRASH_UNUSED1 = 0
const VAL_TRASH_UNUSED2 = 1
const VAL_TRASH_UNUSED3 = 2
const VAL_TRASH_UNUSED4 = 3
const VAL_TRASH_HEALTH = 4
const VAL_TRASH_MAXHEALTH = 5
const VAL_TRASH_UNUSED7 = 6
const VAL_TRASH_MATERIAL = 7
const VAL_TRAP_SPELL = 0
const VAL_TRAP_HITPOINTS = 1
const VAL_TRAP_UNUSED3 = 2
const VAL_TRAP_UNUSED4 = 3
const VAL_TRAP_HEALTH = 4
const VAL_TRAP_MAXHEALTH = 5
const VAL_TRAP_UNUSED7 = 6
const VAL_TRAP_MATERIAL = 7
const VAL_CONTAINER_CAPACITY = 0
const VAL_CONTAINER_FLAGS = 1
const VAL_CONTAINER_KEY = 2
const VAL_CONTAINER_CORPSE = 3
const VAL_CONTAINER_HEALTH = 4
const VAL_CONTAINER_MAXHEALTH = 5
const VAL_CONTAINER_UNUSED7 = 6
const VAL_CONTAINER_MATERIAL = 7
const VAL_CONTAINER_OWNER = 8
const VAL_NOTE_LANGUAGE = 0
const VAL_NOTE_UNUSED2 = 1
const VAL_NOTE_UNUSED3 = 2
const VAL_NOTE_UNUSED4 = 3
const VAL_NOTE_HEALTH = 4
const VAL_NOTE_MAXHEALTH = 5
const VAL_NOTE_UNUSED7 = 6
const VAL_NOTE_MATERIAL = 7
const VAL_DRINKCON_CAPACITY = 0
const VAL_DRINKCON_HOWFULL = 1
const VAL_DRINKCON_LIQUID = 2
const VAL_DRINKCON_POISON = 3
const VAL_DRINKCON_HEALTH = 4
const VAL_DRINKCON_MAXHEALTH = 5
const VAL_DRINKCON_UNUSED7 = 6
const VAL_DRINKCON_MATERIAL = 7
const VAL_KEY_UNUSED1 = 0
const VAL_KEY_UNUSED2 = 1
const VAL_KEY_KEYCODE = 2
const VAL_KEY_UNUSED4 = 3
const VAL_KEY_HEALTH = 4
const VAL_KEY_MAXHEALTH = 5
const VAL_KEY_UNUSED7 = 6
const VAL_KEY_MATERIAL = 7
const VAL_FOOD_FOODVAL = 0
const VAL_FOOD_UNUSED2 = 1
const VAL_FOOD_UNUSED3 = 2
const VAL_FOOD_POISON = 3
const VAL_FOOD_HEALTH = 4
const VAL_FOOD_MAXHEALTH = 5
const VAL_FOOD_UNUSED7 = 6
const VAL_FOOD_MATERIAL = 7
const VAL_MONEY_SIZE = 0
const VAL_MONEY_UNUSED2 = 1
const VAL_MONEY_UNUSED3 = 2
const VAL_MONEY_UNUSED4 = 3
const VAL_MONEY_HEALTH = 4
const VAL_MONEY_MAXHEALTH = 5
const VAL_MONEY_UNUSED7 = 6
const VAL_MONEY_MATERIAL = 7
const VAL_PEN_UNUSED1 = 0
const VAL_PEN_UNUSED2 = 1
const VAL_PEN_UNUSED3 = 2
const VAL_PEN_UNUSED4 = 3
const VAL_PEN_HEALTH = 4
const VAL_PEN_MAXHEALTH = 5
const VAL_PEN_UNUSED7 = 6
const VAL_PEN_MATERIAL = 7
const VAL_BOAT_UNUSED1 = 0
const VAL_BOAT_UNUSED2 = 1
const VAL_BOAT_UNUSED3 = 2
const VAL_BOAT_UNUSED4 = 3
const VAL_BOAT_HEALTH = 4
const VAL_BOAT_MAXHEALTH = 5
const VAL_BOAT_UNUSED7 = 6
const VAL_BOAT_MATERIAL = 7
const VAL_FOUNTAIN_CAPACITY = 0
const VAL_FOUNTAIN_HOWFULL = 1
const VAL_FOUNTAIN_LIQUID = 2
const VAL_FOUNTAIN_POISON = 3
const VAL_FOUNTAIN_HEALTH = 4
const VAL_FOUNTAIN_MAXHEALTH = 5
const VAL_FOUNTAIN_UNUSED7 = 6
const VAL_FOUNTAIN_MATERIAL = 7
const VAL_VEHICLE_ROOM = 0
const VAL_VEHICLE_UNUSED2 = 1
const VAL_VEHICLE_UNUSED3 = 2
const VAL_VEHICLE_APPEAR = 3
const VAL_VEHICLE_HEALTH = 4
const VAL_VEHICLE_MAXHEALTH = 5
const VAL_VEHICLE_UNUSED7 = 6
const VAL_VEHICLE_MATERIAL = 7
const VAL_HATCH_DEST = 0
const VAL_HATCH_FLAGS = 1
const VAL_HATCH_DCSKILL = 2
const VAL_HATCH_DCMOVE = 3
const VAL_HATCH_HEALTH = 4
const VAL_HATCH_MAXHEALTH = 5
const VAL_HATCH_UNUSED7 = 6
const VAL_HATCH_MATERIAL = 7
const VAL_HATCH_DCLOCK = 8
const VAL_HATCH_DCHIDE = 9
const VAL_WINDOW_UNUSED1 = 0
const VAL_WINDOW_UNUSED2 = 1
const VAL_WINDOW_UNUSED3 = 2
const VAL_WINDOW_UNUSED4 = 3
const VAL_WINDOW_HEALTH = 4
const VAL_WINDOW_MAXHEALTH = 5
const VAL_WINDOW_UNUSED7 = 6
const VAL_WINDOW_MATERIAL = 7
const VAL_CONTROL_UNUSED1 = 0
const VAL_CONTROL_UNUSED2 = 1
const VAL_CONTROL_UNUSED3 = 2
const VAL_CONTROL_UNUSED4 = 3
const VAL_CONTROL_HEALTH = 4
const VAL_CONTROL_MAXHEALTH = 5
const VAL_CONTROL_UNUSED7 = 6
const VAL_CONTROL_MATERIAL = 7
const VAL_PORTAL_DEST = 0
const VAL_PORTAL_DCSKILL = 1
const VAL_PORTAL_DCMOVE = 2
const VAL_PORTAL_APPEAR = 3
const VAL_PORTAL_HEALTH = 4
const VAL_PORTAL_MAXHEALTH = 5
const VAL_PORTAL_UNUSED7 = 6
const VAL_PORTAL_MATERIAL = 7
const VAL_PORTAL_DCLOCK = 8
const VAL_PORTAL_DCHIDE = 9
const VAL_BOARD_READ = 0
const VAL_BOARD_WRITE = 1
const VAL_BOARD_ERASE = 2
const VAL_BOARD_UNUSED4 = 3
const VAL_BOARD_HEALTH = 4
const VAL_BOARD_MAXHEALTH = 5
const VAL_BOARD_UNUSED7 = 6
const VAL_BOARD_MATERIAL = 7
const VAL_DOOR_DCLOCK = 8
const VAL_DOOR_DCHIDE = 9
const VAL_CORPSE_HEAD = 8
const VAL_CORPSE_RARM = 9
const VAL_CORPSE_LARM = 10
const VAL_CORPSE_RLEG = 11
const VAL_CORPSE_LLEG = 12
const VAL_GROWTH = 0
const VAL_MATGOAL = 1
const VAL_MATURITY = 2
const VAL_MAXMATURE = 3
const VAL_WATERLEVEL = 6
const VAL_SOILQ = 8
const LEVELTYPE_CLASS = 1
const LEVELTYPE_RACE = 2

type extra_descr_data struct {
	Keyword     *byte
	Description *byte
	Next        *extra_descr_data
}
type obj_affected_type struct {
	Location int
	Specific int
	Modifier int
}
type obj_spellbook_spell struct {
	Spellname int
	Pages     int
}
type obj_data struct {
	Item_number        obj_vnum
	In_room            room_rnum
	Room_loaded        room_vnum
	Value              [16]int
	Type_flag          int8
	Level              int
	Wear_flags         [4]int
	Extra_flags        [4]bitvector_t
	Weight             int64
	Cost               int
	Cost_per_day       int
	Timer              int
	Bitvector          [4]bitvector_t
	Size               int
	Affected           [6]obj_affected_type
	Name               *byte
	Description        *byte
	Short_description  *byte
	Action_description *byte
	Ex_description     *extra_descr_data
	Carried_by         *char_data
	Worn_by            *char_data
	Worn_on            int16
	In_obj             *obj_data
	Contains           *obj_data
	Id                 int32
	Generation         libc.Time
	Unique_id          int64
	Proto_script       *trig_proto_list
	Script             *script_data
	Next_content       *obj_data
	Next               *obj_data
	Sbinfo             *obj_spellbook_spell
	Sitting            *char_data
	Scoutfreq          int
	Lload              libc.Time
	Healcharge         int
	Kicharge           int64
	Kitype             int
	User               *char_data
	Target             *char_data
	Distance           int
	Foob               int
	Aucter             int32
	CurBidder          int32
	AucTime            libc.Time
	Bid                int
	Startbid           int
	Auctname           *byte
	Posttype           int
	Posted_to          *obj_data
	Fellow_wall        *obj_data
}
type room_direction_data struct {
	General_description *byte
	Keyword             *byte
	Exit_info           bitvector_t
	Key                 obj_vnum
	To_room             room_rnum
	Dclock              int
	Dchide              int
	Dcskill             int
	Dcmove              int
	Failsavetype        int
	Dcfailsave          int
	Failroom            int
	Totalfailroom       int
}
type room_data struct {
	Number         room_vnum
	Zone           zone_rnum
	Sector_type    int
	Name           *byte
	Description    *byte
	Ex_description *extra_descr_data
	Dir_option     [12]*room_direction_data
	Room_flags     [4]bitvector_t
	Proto_script   *trig_proto_list
	Script         *script_data
	Light          int8
	Func           func(ch *char_data, me unsafe.Pointer, cmd int, argument *byte) int
	Contents       *obj_data
	People         *char_data
	Timed          int
	Dmg            int
	Gravity        int
	Geffect        int
}
type memory_rec_struct struct {
	Id   int32
	Next *memory_rec_struct
}
type memory_rec memory_rec_struct
type time_info_data struct {
	Hours int
	Day   int
	Month int
	Year  int16
}
type time_data struct {
	Birth   libc.Time
	Created libc.Time
	Maxage  libc.Time
	Logon   libc.Time
	Played  libc.Time
}
type pclean_criteria_data struct {
	Level int
	Days  int
}
type abil_data struct {
	Str   int8
	Intel int8
	Wis   int8
	Dex   int8
	Con   int8
	Cha   int8
}
type player_special_data struct {
	Poofin                 *byte
	Poofout                *byte
	Aliases                *alias_data
	Last_tell              int32
	Last_olc_targ          unsafe.Pointer
	Last_olc_mode          int
	Host                   *byte
	Spell_level            [10]int
	Memcursor              int
	Wimp_level             int
	Freeze_level           int8
	Invis_level            int16
	Load_room              room_vnum
	Pref                   [4]bitvector_t
	Bad_pws                uint8
	Conditions             [3]int8
	Skill_points           int
	Class_skill_points     [31]int
	Comm_hist              [10]*txt_block
	Olc_zone               int
	Gauntlet               int
	Speaking               int
	Tlevel                 int
	Ability_trains         int
	Spellmem               [100]int
	Feat_points            int
	Epic_feat_points       int
	Class_feat_points      [31]int
	Epic_class_feat_points [31]int
	Domain                 [37]int
	School                 [10]int
	Deity                  int
	Spell_mastery_points   int
	Color_choices          [16]*byte
	Page_length            uint8
	Murder                 int
	Trainstr               int
	Trainint               int
	Traincon               int
	Trainwis               int
	Trainagl               int
	Trainspd               int
	Carrying               *char_data
	Carried_by             *char_data
	Racial_pref            int
}
type memorize_node struct {
	Timer int
	Spell int
	Next  *memorize_node
}
type innate_node struct {
	Timer    int
	Spellnum int
	Next     *innate_node
}
type mob_special_data struct {
	Memory      *memory_rec
	Attack_type int8
	Default_pos int8
	Damnodice   int8
	Damsizedice int8
	Newitem     int
}
type affected_type struct {
	Type      int16
	Duration  int16
	Modifier  int
	Location  int
	Specific  int
	Bitvector bitvector_t
	Next      *affected_type
}
type queued_act struct {
	Level    int
	Spellnum int
}
type follow_type struct {
	Follower *char_data
	Next     *follow_type
}
type level_learn_entry struct {
	Next     *level_learn_entry
	Location int
	Specific int
	Value    int8
}
type levelup_data struct {
	Next                 *levelup_data
	Prev                 *levelup_data
	Type                 int8
	Spec                 int8
	Level                int8
	Hp_roll              int8
	Mana_roll            int8
	Ki_roll              int8
	Move_roll            int8
	Accuracy             int8
	Fort                 int8
	Reflex               int8
	Will                 int8
	Add_skill            int8
	Add_gen_feats        int8
	Add_epic_feats       int8
	Add_class_feats      int8
	Add_class_epic_feats int8
	Skills               *level_learn_entry
	Feats                *level_learn_entry
}
type char_data struct {
	Pfilepos           int
	Nr                 mob_rnum
	In_room            room_rnum
	Was_in_room        room_rnum
	Wait               int
	Name               *byte
	Short_descr        *byte
	Long_descr         *byte
	Description        *byte
	Title              *byte
	Size               int
	Sex                int8
	Race               int8
	Hairl              int8
	Hairs              int8
	Hairc              int8
	Skin               int8
	Eye                int8
	Distfea            int8
	Race_level         int
	Level_adj          int
	Chclass            int8
	Chclasses          [31]int
	Epicclasses        [31]int
	Level_info         *levelup_data
	Level              int
	Admlevel           int
	Admflags           [4]bitvector_t
	Hometown           room_vnum
	Time               time_data
	Weight             uint8
	Height             uint8
	Real_abils         abil_data
	Aff_abils          abil_data
	Player_specials    *player_special_data
	Mob_specials       mob_special_data
	Affected           *affected_type
	Affectedv          *affected_type
	Actq               *queued_act
	Equipment          [23]*obj_data
	Carrying           *obj_data
	Desc               *descriptor_data
	Id                 int32
	Proto_script       *trig_proto_list
	Script             *script_data
	Memory             *script_memory
	Next_in_room       *char_data
	Next               *char_data
	Next_fighting      *char_data
	Next_affect        *char_data
	Next_affectv       *char_data
	Followers          *follow_type
	Master             *char_data
	Master_id          int32
	Memorized          *memorize_node
	Innate             *innate_node
	Fighting           *char_data
	Position           int8
	Carry_weight       int
	Carry_items        int8
	Timer              int
	Sits               *obj_data
	Blocks             *char_data
	Blocked            *char_data
	Absorbing          *char_data
	Absorbby           *char_data
	Feats              [751]int8
	Combat_feats       [6][4]int
	School_feats       [2]int
	Skills             [1001]int8
	Skillmods          [1001]int8
	Skillperfs         [1001]int8
	Alignment          int
	Alignment_ethic    int
	Idnum              int32
	Act                [4]bitvector_t
	Affected_by        [4]int
	Bodyparts          [4]int
	Saving_throw       [3]int16
	Apply_saving_throw [3]int16
	Powerattack        int
	Combatexpertise    int
	Mana               int64
	Max_mana           int64
	Hit                int64
	Max_hit            int64
	Move               int64
	Max_move           int64
	Ki                 int64
	Max_ki             int64
	Armor              int
	Shield_bonus       int16
	Gold               int
	Bank_gold          int
	Exp                int64
	Accuracy           int
	Accuracy_mod       int
	Damage_mod         int
	Spellfail          int16
	Armorcheck         int16
	Armorcheckall      int16
	Basepl             int64
	Baseki             int64
	Basest             int64
	Charge             int64
	Chargeto           int64
	Barrier            int64
	Clan               *byte
	Droom              room_vnum
	Choice             int
	Sleeptime          int
	Foodr              int
	Altitude           int
	Overf              int
	Spam               int
	Radar1             room_vnum
	Radar2             room_vnum
	Radar3             room_vnum
	Ship               int
	Shipr              room_vnum
	Lastpl             libc.Time
	Lboard             [5]libc.Time
	Listenroom         room_vnum
	Crank              int
	Kaioken            int
	Absorbs            int
	Boosts             int
	Upgrade            int
	Lastint            libc.Time
	Majinize           int
	Fury               int16
	Btime              int16
	Eavesdir           int
	Deathtime          libc.Time
	Rp                 int
	Suppression        int64
	Suppressed         int64
	Drag               *char_data
	Dragged            *char_data
	Trp                int
	Mindlink           *char_data
	Lasthit            int
	Dcount             int
	Voice              *byte
	Limbs              [4]int
	Aura               int
	Rewtime            libc.Time
	Grappling          *char_data
	Grappled           *char_data
	Grap               int
	Genome             [2]int
	Combo              int
	Lastattack         int
	Combhits           int
	Ping               int
	Starphase          int
	Mimic              int
	Bonuses            [52]int
	Ccpoints           int
	Negcount           int
	Cooldown           int
	Death_type         int
	Moltexp            int64
	Moltlevel          int
	Loguser            *byte
	Arenawatch         int
	Majinizer          int64
	Speedboost         int
	Skill_slots        int
	Tail_growth        int
	Rage_meter         int
	Feature            *byte
	Transclass         int
	Transcost          [6]int
	Armor_last         int
	Forgeting          int
	Forgetcount        int
	Backstabcool       int
	Con_cooldown       int
	Stupidkiss         int16
	Temp_prompt        *byte
	Personality        int
	Combine            int
	Linker             int
	Fishstate          int
	Throws             int
	Defender           *char_data
	Defending          *char_data
	Lifeforce          int64
	Lifeperc           int
	Gooptime           int
	Blesslvl           int
	Poisonby           *char_data
	Mobcharge          int
	Preference         int
	Aggtimer           int
	Lifebonus          int
	Asb                int
	Regen              int
	Rbank              int
	Con_sdcooldown     int
	Limb_condition     [4]int
	Rdisplay           *byte
	Song               int16
	Original           *char_data
	Clones             int16
	Relax_count        int
	IngestLearned      int
}
type txt_block struct {
	Text    *byte
	Aliased int
	Next    *txt_block
}
type txt_q struct {
	Head *txt_block
	Tail *txt_block
}
type descriptor_data struct {
	Descriptor     int
	Host           [41]byte
	Bad_pws        int8
	Idle_tics      int8
	Connected      int
	Desc_num       int
	Login_time     libc.Time
	Showstr_head   *byte
	Showstr_vector **byte
	Showstr_count  int
	Showstr_page   int
	Str            **byte
	Backstr        *byte
	Max_str        uint64
	Mail_to        int32
	Has_prompt     int
	Inbuf          [4096]byte
	Last_input     [2048]byte
	Small_outbuf   [6020]byte
	Output         *byte
	History        **byte
	History_pos    int
	Bufptr         int
	Bufspace       int
	Large_outbuf   *txt_block
	Input          txt_q
	Character      *char_data
	Original       *char_data
	Snooping       *descriptor_data
	Snoop_by       *descriptor_data
	Next           *descriptor_data
	Olc            *oasis_olc_data
	User           *byte
	Email          *byte
	Pass           *byte
	Loadplay       *byte
	Writenew       int
	Total          int
	Rpp            int
	Tmp1           *byte
	Tmp2           *byte
	Tmp3           *byte
	Tmp4           *byte
	Tmp5           *byte
	Level          int
	Newsbuf        *byte
	Obj_editval    int
	Obj_editflag   int
	Obj_was        *byte
	Obj_name       *byte
	Obj_short      *byte
	Obj_long       *byte
	Obj_type       int
	Obj_weapon     int
	Obj_point      *obj_data
	Shipmenu       int
	Shipsize       int
	Ship_name      *byte
	Shipextra      [4]int
	Shields        int
	Armor          int
	Drive          int
	Shipweap       int
	User_freed     int
	Customfile     int
	Title          *byte
	Rbank          int
}
type msg_type struct {
	Attacker_msg *byte
	Victim_msg   *byte
	Room_msg     *byte
}
type message_type struct {
	Die_msg  msg_type
	Miss_msg msg_type
	Hit_msg  msg_type
	God_msg  msg_type
	Next     *message_type
}
type message_list struct {
	A_type            int
	Number_of_attacks int
	Msg               *message_type
}
type social_messg struct {
	Act_nr              int
	Command             *byte
	Sort_as             *byte
	Hide                int
	Min_victim_position int
	Min_char_position   int
	Min_level_char      int
	Char_no_arg         *byte
	Others_no_arg       *byte
	Char_found          *byte
	Others_found        *byte
	Vict_found          *byte
	Char_body_found     *byte
	Others_body_found   *byte
	Vict_body_found     *byte
	Not_found           *byte
	Char_auto           *byte
	Others_auto         *byte
	Char_obj_found      *byte
	Others_obj_found    *byte
}
type weather_data struct {
	Pressure int
	Change   int
	Sky      int
	Sunlight int
}
type index_data struct {
	Vnum   mob_vnum
	Number int
	Func   func(ch *char_data, me unsafe.Pointer, cmd int, argument *byte) int
	Farg   *byte
	Proto  *trig_data
}
type trig_proto_list struct {
	Vnum int
	Next *trig_proto_list
}
type guild_info_type struct {
	Pc_class   int
	Guild_room room_vnum
	Direction  int
}
type game_data struct {
	Pk_allowed          int
	Pt_allowed          int
	Level_can_shout     int
	Holler_move_cost    int
	Tunnel_size         int
	Max_exp_gain        int
	Max_exp_loss        int
	Max_npc_corpse_time int
	Max_pc_corpse_time  int
	Idle_void           int
	Idle_rent_time      int
	Idle_max_level      int
	Dts_are_dumps       int
	Load_into_inventory int
	Track_through_doors int
	Level_cap           int
	Stack_mobs          int
	Stack_objs          int
	Mob_fighting        int
	OK                  *byte
	NOPERSON            *byte
	NOEFFECT            *byte
	Disp_closed_doors   int
	Reroll_player       int
	Initial_points      int
	Enable_compression  int
	Enable_languages    int
	All_items_unique    int
	Exp_multiplier      float32
}
type crash_save_data struct {
	Free_rent          int
	Max_obj_save       int
	Min_rent_cost      int
	Auto_save          int
	Autosave_time      int
	Crash_file_timeout int
	Rent_file_timeout  int
}
type room_numbers struct {
	Mortal_start_room room_vnum
	Immort_start_room room_vnum
	Frozen_start_room room_vnum
	Donation_room_1   room_vnum
	Donation_room_2   room_vnum
	Donation_room_3   room_vnum
}
type game_operation struct {
	DFLT_PORT          uint16
	DFLT_IP            *byte
	DFLT_DIR           *byte
	LOGNAME            *byte
	Max_playing        int
	Max_filesize       int
	Max_bad_pws        int
	Siteok_everyone    int
	Nameserver_is_slow int
	Use_new_socials    int
	Auto_save_olc      int
	MENU               *byte
	WELC_MESSG         *byte
	START_MESSG        *byte
	Imc_enabled        int
}
type autowiz_data struct {
	Use_autowiz     int
	Min_wizlist_lev int
}
type tick_data struct {
	Pulse_violence int
	Pulse_mobile   int
	Pulse_zone     int
	Pulse_autosave int
	Pulse_idlepwd  int
	Pulse_sanity   int
	Pulse_usage    int
	Pulse_timesave int
	Pulse_current  int
}
type advance_data struct {
	Allow_multiclass int
	Allow_prestige   int
}
type creation_data struct {
	Method int
}
type config_data struct {
	CONFFILE  *byte
	Play      game_data
	Csd       crash_save_data
	Room_nums room_numbers
	Operation game_operation
	Autowiz   autowiz_data
	Advance   advance_data
	Ticks     tick_data
	Creation  creation_data
}
type aging_data struct {
	Adult     int
	Classdice [3][2]int
	Middle    int
	Old       int
	Venerable int
	Maxdice   [2]int
}
