package main

const EDIT_NONE = 0
const EDIT_CUSTOM = 1
const EDIT_RESTRING = 2
const EDIT_CUSTOM_MAIN = 1
const EDIT_CUSTOM_NAME = 2
const EDIT_CUSTOM_SDESC = 3
const EDIT_CUSTOM_LDESC = 4
const EDIT_CUSTOM_TYPE = 5
const EDIT_CUSTOM_WEAPON = 6
const EDIT_CUSTOM_QUIT = 7
const EDIT_RESTRING_MAIN = 1
const EDIT_RESTRING_NAME = 2
const EDIT_RESTRING_SDESC = 3
const EDIT_RESTRING_LDESC = 4
const EDIT_RESTRING_QUIT = 5
const EDIT_RESTRING_CONF = 6
