package main

const NUM_TRIG_TYPE_FLAGS = 20
const TRIGEDIT_MAIN_MENU = 0
const TRIGEDIT_TRIGTYPE = 1
const TRIGEDIT_CONFIRM_SAVESTRING = 2
const TRIGEDIT_NAME = 3
const TRIGEDIT_INTENDED = 4
const TRIGEDIT_TYPES = 5
const TRIGEDIT_COMMANDS = 6
const TRIGEDIT_NARG = 7
const TRIGEDIT_ARGUMENT = 8
const TRIGEDIT_COPY = 9
const OLC_SCRIPT_EDIT = 82766
const SCRIPT_MAIN_MENU = 0
const SCRIPT_NEW_TRIGGER = 1
const SCRIPT_DEL_TRIGGER = 2
